version: '3.0'

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.11.10-management
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBIT_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_PASSWORD}
    ports:
      - ${RABBIT_HOST_PORT}:${RABBIT_PORT}
      - ${RABBIT_MANAGE_HOST_PORT}:${RABBIT_MANAGE_PORT}
    volumes:
      - homepp_rabbitmq_data:/var/lib/rabbitmq
    restart: on-failure
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5
  postgres:
    container_name: postgres
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=${POSTGRESQL_USER}
      - POSTGRES_PASSWORD=${POSTGRESQL_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 3s
      retries: 5
    volumes:
      - ./db/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
      - pgdata:/var/lib/postgresql/data
  api:
    container_name: api
    environment:
      - POSTGRESQL_USER=${POSTGRESQL_USER}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRESQL_HOST=postgres
      - POSTGRESQL_PORT=${POSTGRESQL_PORT}
      - POSTGRESQL_BASE=api
      - API_HOST=api
      - API_PORT=${API_PORT}
      - BROKER_PROTOCOL=amqp
      - BROKER_USERNAME=${RABBIT_USERNAME}
      - BROKER_PASSWORD=${RABBIT_PASSWORD}
      - BROKER_HOST=rabbitmq
      - BROKER_PORT=${RABBIT_PORT}

    build:
      context: ./api-go
    ports:
      - ${API_HOST_PORT}:${API_PORT}
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy
  aggregator:
    container_name: aggregator
    hostname: aggregator
    environment:
      - AGGREGATOR_HOST=aggregator
      - AGGREGATOR_PORT=${AGGREGATOR_PORT}
      - BROKER_PROTOCOL=amqp
      - BROKER_USERNAME=${RABBIT_USERNAME}
      - BROKER_PASSWORD=${RABBIT_PASSWORD}
      - BROKER_HOST=rabbitmq
      - BROKER_PORT=${RABBIT_PORT}
      - API_PROTOCOL=http
      - API_HOST=api
      - API_PORT=${API_PORT}
    build:
      context: ./aggregator
    ports:
      - ${AGGREGATOR_HOST_PORT}:${AGGREGATOR_PORT}
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy
  frontend:
    container_name: frontend
    build:
      context: ./homepp_front
    ports: 
      - 80:80
    depends_on:
      api: 
        condition: service_started
      aggregator:
        condition: service_started


volumes:
  redis_data:
    driver: local
  pgdata:
  homepp_rabbitmq_data: